# Generated by Django 3.1.3 on 2021-09-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communicationSystem', '0002_auto_20210721_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittedBy', models.CharField(max_length=11)),
                ('submission', models.FileField(upload_to='communicationSystem/assignmentsSubmitted')),
                ('submissionDate', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communicationSystem.assignment')),
            ],
        ),
    ]
