# Generated by Django 3.1.3 on 2021-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationSystem', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
