# Generated by Django 3.1.3 on 2021-09-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communicationSystem', '0004_auto_20210919_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submissionDate',
        ),
    ]
