# Generated by Django 3.1.3 on 2021-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationSystem', '0005_remove_submission_submissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submissionDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
