# Generated by Django 3.1.3 on 2021-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210312_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sem8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('mid_sem', models.TextField()),
                ('end_sem', models.TextField(default='')),
                ('practicals', models.TextField(default='')),
            ],
        ),
    ]
