# Generated by Django 3.1.3 on 2021-05-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
