# Generated by Django 3.1.3 on 2021-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceSystem', '0003_auto_20210626_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='rollNo',
            field=models.CharField(default='', max_length=11),
        ),
    ]
